# Nome do seu Workflow. É o que aparecerá na aba "Actions"
name: CI - Build e Test

on:
  push:
    branches: [ "main" ] 

jobs:
  build_e_test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4 

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 
          
      - name: Instalar dependências
        run: npm install 
        
      - name: Executar Testes
        run: npm test 
        
      # Esta step só seria necessária para construir o app para iOS ou Android (mais complexo)
      # - name: Construir o bundle React Native (Exemplo)
      #   run: npm run build